name: 'Documentation'

on: [push, pull_request]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: 'Cache'
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: 'Install'
        run: pip install -r docs/requirements.txt
      - name: 'Build'
        run: mkdocs build --verbose --clean --strict

  deploy:
    if: github.event_name == 'push' && contains(fromJson('["refs/heads/master", "refs/heads/main"]'), github.ref)
    needs: build
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: 'Cache'
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: 'Install'
        run: pip install -r docs/requirements.txt
      - name: 'Deploy'
        run: mkdocs gh-deploy --force --verbose --clean --strict
